version: "3"
services:
  app:
    image: webdevops/php-nginx:7.4
    ports:
      - 8000:80
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      DB_NAME: database
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql: